#! /usr/bin/env /usr/bin/python3.7
# -*- coding: utf8 -*-
threshold = {
    'default': {
        'UnhealthyServerCount': [0, 'Average', 'greater'],
        'TrafficRXNew': [0.8, 'Average', 'greater'],
        'TrafficTXNew': [0.8, 'Average', 'greater'],
        'DropConnection': [0, 'Average', 'greater'],
        'DropPacketRX': [0, 'Average', 'greater'],
        'DropPacketTX': [0, 'Average', 'greater'],
        'DropTrafficRX': [0, 'Average', 'greater'],
        'DropTrafficTX': [0, 'Average', 'greater'],
        'InstanceDropConnection': [0, 'Average', 'greater'],
        'InstanceDropPacketRX': [0, 'Average', 'greater'],
        'InstanceDropPacketTX': [0, 'Average', 'greater'],
        'InstanceDropTrafficRX': [0, 'Average', 'greater'],
        'InstanceDropTrafficTX': [0, 'Average', 'greater'],
        'StatusCode4xx': [10, 'Average', 'greater'],
        'StatusCode5xx': [10, 'Average', 'greater'],
        'Rt': [1000, 'Average', 'greater'],
    }
}

metric_description = {
    'HealthyServerCount': 'slb 后端健康实例数',
    'UnhealthyServerCount': 'slb 后端异常实例数',
    'PacketTX': 'slb 端口每秒流出数据包数',
    'PacketRX': 'slb 端口每秒流入数据包数',
    'TrafficRXNew': 'slb 端口每秒流入数据量',
    'TrafficTXNew': 'slb 端口每秒流出数据量',
    'ActiveConnection': 'slb 端口活跃连接数',
    'InactiveConnection': 'slb 端口非活跃连接数',
    'NewConnection': 'slb 端口新建连接数',
    'MaxConnection': 'slb 端口并发连接数',
    'DropConnection': 'slb 监听每秒丢失连接数',
    'DropPacketRX': 'slb 监听每秒丢失入包数',
    'DropPacketTX': 'slb 监听每秒丢失出包数',
    'DropTrafficRX': 'slb 监听每秒丢失入bit数',
    'DropTrafficTX': 'slb 监听每秒丢失出bit数',
    'InstanceActiveConnection': 'slb 实例每秒活跃连接数',
    'InstanceDropConnection': 'slb 实例每秒丢失连接数',
    'InstanceDropPacketRX': 'slb 实例每秒丢失入包数',
    'InstanceDropPacketTX': 'slb 实例每秒丢失出包数',
    'InstanceDropTrafficRX': 'slb 实例每秒丢失入bit数',
    'InstanceDropTrafficTX': 'slb 实例每秒丢失出bit数',
    'InstanceInactiveConnection': 'slb 实例每秒非活跃连接数',
    'InstanceMaxConnection': 'slb 实例每秒最大并发连接数',
    'InstanceNewConnection': 'slb 实例每秒新建连接数',
    'InstancePacketRX': 'slb 实例每秒入包数',
    'InstancePacketTX': 'slb 实例每秒出包数',
    'InstanceTrafficRX': 'slb 实例每秒入bit数',
    'InstanceTrafficTX': 'slb 实例每秒出bit数',
    'StatusCode4xx': 'slb 4xx状态码统计',
    'StatusCode5xx': 'slb 5xx状态码统计',
    'Rt': '实例平均响应时长Rt',
}
